version: "3.8"

networks:
  livewire_tables:
    driver: bridge

services:
  php-apache:
    restart: always
    build: .docker/php-apache
    ports:
      - ${DOCKER_APP_PORT}:80
      - ${DOCKER_APP_SSL_PORT}:443
    volumes:
      - .:/var/www/html
      - .docker/php-apache/etc/letsencrypt:/etc/letsencrypt
    networks:
      - livewire_tables
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - ${DOCKER_DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - livewire_tables

volumes:
  mysql-volume:
